concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

name: Build IceRaven Dark Theme

on:
  workflow_dispatch:
  schedule:
    - cron: '00 0 * * *'

permissions:
  releases: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget apktool zipalign apksigner jq openjdk-17-jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Get IceRaven Version
        run: |
          ICERAVEN_VERSION="2.26.0" # Replace with desired version
          echo "ICERAVEN_VERSION=$ICERAVEN_VERSION" >> $GITHUB_ENV
      - name: Download IceRaven APK
        run: |
          wget -q "https://github.com/fork-maintainers/iceraven-browser/releases/download/iceraven-${{ env.ICERAVEN_VERSION }}/iceraven-${{ env.ICERAVEN_VERSION }}-browser-arm64-v8a-forkRelease.apk" -O iceraven.apk
      - name: Run Build Script
        run: bash build.sh ${{ env.ICERAVEN_VERSION }} || { echo "Build script failed"; exit 1; }
      - name: Sign APK
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -di > keystore.jks
          apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSPHRASE }} --key-pass pass:${{ secrets.KEY_PASSWORD }} iceraven-patched-signed.apk || { echo "Signing failed"; exit 1; }
      - name: Release APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: iceraven-dark-${{ env.ICERAVEN_VERSION }}
          files: iceraven-patched-signed.apk
