name: Iceraven OLED Builder

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Fetch latest APK
        id: get-apk
        run: |
          TAG=$(curl -s https://api.github.com/repos/fork-maintainers/iceraven-browser/releases/latest | jq -r '.tag_name')
          echo "TAG=$TAG" >> $GITHUB_ENV
          wget -q "https://github.com/fork-maintainers/iceraven-browser/releases/download/$TAG/iceraven-$TAG-arm64-v8a-forkRelease.apk" -O iceraven.apk

      - name: Prepare keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > keystore.jks
          echo "KEYSTORE=keystore.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASS=${{ secrets.KEYSTORE_PASS }}" >> $GITHUB_ENV

      - name: Build modified APK
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          tag_name: ${{ env.TAG }}-oled
          files: iceraven-oled.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
