name: build apk
on:
  workflow_dispatch:
  schedule:
    - cron: '00 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release info
        id: getLatest
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y jq
      - name: Get latest IceRaven release version
        run: |
          echo "BUILD_VERSION=$(curl -s https://github.com/fork-maintainers/iceraven-browser/releases/latest | grep -o 'tag/iceraven-[^"]*' | head -n 1 | cut -d/ -f2 | sed 's/iceraven-//')" >> $GITHUB_ENV
      - name: Check if latest version was already built
        if: ${{ steps.getLatest.outputs.tag_name == env.BUILD_VERSION }}
        run: |
          echo latest version already built and released
          exit -1
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y wget apktool zipalign
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run build script
        run: |
          cd ${{ github.workspace }}
          chmod +x ./build.sh
          ./build.sh
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.BUILD_VERSION }}
          files: ${{ github.workspace }}/patched_signed.apk
