name: Build and Modify APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install apktool
      run: sudo apt-get install -y apktool

    - name: Install apksigner
      run: sudo apt-get install -y apksigner

    - name: Download Iceraven APK
      run: wget -O iceraven.apk https://github.com/fork-maintainers/iceraven-browser/releases/download/iceraven-2.26.0/iceraven-2.26.0-browser-arm64-v8a-forkRelease.apk

    - name: Run build script
      run: ./build.sh
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

    - name: Upload signed APK
      uses: actions/upload-artifact@v2
      with:
        name: iceraven-signed
        path: iceraven-signed.apk
