name: Build IceRaven Dark Theme

on:
  workflow_dispatch:
  schedule:
    - cron: '00 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget apktool zipalign apksigner jq
      - name: Get IceRaven Version
        run: |
          ICERAVEN_VERSION="2.26.0" # Replace with desired version
          echo "ICERAVEN_VERSION=$ICERAVEN_VERSION" >> $GITHUB_ENV
      - name: Download IceRaven APK
        run: |
          wget -q "https://github.com/fork-maintainers/iceraven-browser/releases/download/iceraven-${{ env.ICERAVEN_VERSION }}/iceraven-${{ env.ICERAVEN_VERSION }}-browser-arm64-v8a-forkRelease.apk" -O iceraven.apk
      - name: Run Build Script
        run: bash build.sh ${{ env.ICERAVEN_VERSION }}
      - name: Sign APK  # Important: Configure signing secrets
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -di > keystore.jks
          apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSPHRASE }} --key-pass pass:${{ secrets.KEY_PASSWORD }} iceraven-patched-signed.apk
      - name: Release APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: iceraven-dark-${{ env.ICERAVEN_VERSION }}
          files: iceraven-patched-signed.apk
